### ISSUE TITLE
Support Spring Boot 1.3.x

### ISSUE THREAD

**Issue by binkley** [jmnarloch/zuul-route-health-spring-cloud-starter#1]
I note the dependencies are around Spring Boot 1.2.x.  Any plans to upgrade to 1.3.x?  Or, perhaps, it already works "as is"?

I did get this with "mvn spring-boot:run" and am investigating if I caused it:

```
Caused by: java.lang.NoClassDefFoundError: org/springframework/context/event/GenericApplicationListener
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
    at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:407)
    ... 7 more
Caused by: java.lang.ClassNotFoundException: org.springframework.context.event.GenericApplicationListener
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

**Comment by jmnarloch** [comment]
Yes definitely, when Spring Cloud 1.1 will be released.

General rule of thumb when using Spring Cloud and Spring Boot - don't mess up your classpath with incompatible versions. If you use Spring Cloud in version 1.0.x stick to the Spring Boot and Spring Framework provided by them.

More deliberate read: https://spring.io/blog/2015/11/25/migrating-spring-cloud-apps-from-spring-boot-1-2-to-1-3
